### ISSUE TITLE
Can't download using URLs_ADULT_SAMPLE

### ISSUE THREAD

**Issue by stevebit** [henry090/fastai#105]
Hi,
I receive the following error when I try to download the data using URLs_ADULT_SAMPLE().

Error: $ operator is invalid for atomic vectors

Can somebody please assist

**Comment by henry090** [comment]
Hi Steve. Did you follow our installation guide on the top of the readme https://github.com/henry090/fastai ?

**Comment by stevebit** [comment]
Yep, I followed the installation steps 1 to 4.  It also looks like the fastai library loads correctly.  I'm currently installing in on MacOS High Sierra and using the following R version.

platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night

**Comment by henry090** [comment]
Could you install the library from GitHub and see the output of  ```fastai::fastai_version()```

**Comment by stevebit** [comment]
Error: Python module fastai was not found.

Detected Python configuration:

python:         /opt/anaconda3/envs/python37/bin/python
libpython:      /opt/anaconda3/envs/python37/lib/libpython3.7m.dylib
pythonhome:     /opt/anaconda3/envs/python37:/opt/anaconda3/envs/python37
version:        3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /opt/anaconda3/envs/python37/lib/python3.7/site-packages/numpy
numpy_version:  1.18.1
fastai:         [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON

**Comment by henry090** [comment]
Try to find with reticulate the python in which you installed fastai. And then set that python with reticulate use python (required=TRUE)

**Comment by stevebit** [comment]
got it working thanks for you help.  It required me to install fastai for python a few times.

**Comment by henry090** [comment]
Glad, that you could fix your issue!
