### ISSUE TITLE
Error when using model$export()

### ISSUE THREAD

**Issue by Cdk29** [henry090/fastai#106]
When training a model like [in this notebook](https://github.com/Cdk29/Cassava/blob/main/Bug_method_export.Rmd) or [here (md doc to got the session infos)](https://github.com/Cdk29/Cassava/blob/main/Xresnet.md). 

I got the following error from python : 
```

Quitting from lines 106-107 (Bug_method_export.Rmd) 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: Can't pickle local object 'make_python_function.<locals>.python_function'

Detailed traceback: 
  File "/home/erolland/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/fastai/learner.py", line 542, in export
    torch.save(self, self.path/fname, pickle_protocol=pickle_protocol)
  File "/home/erolland/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/torch/serialization.py", line 372, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/erolland/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/torch/serialization.py", line 476, in _save
    pickler.dump(obj)
Calls: <Anonymous> ... withVisible -> eval -> eval -> <Anonymous> -> py_call_impl
Exécution arrêtée
```

When I am running : 

`learnR$export(fname = export.pkl)`

The error message came from the first notebook. The second md document provide the session infos().

**Comment by henry090** [comment]
Thanks so much for this issue. I fixed that. However, could you write the metric like this: ```accuracy()``` not ```accuracy``` and see if this will work for you.

**Comment by Cdk29** [comment]
Sorry for the delay, I go into this as soon as I can.

**Comment by Cdk29** [comment]
@henry090 I run it with accuracy() and it worked perfectly.
