### ISSUE TITLE
fastai loading error

### ISSUE THREAD

**Issue by mubashirqasim** [henry090/fastai#109]
Hi there,

Thanks for great work to bring fastai to R.

In step two, after installing fastai from git hub, I am getting the following error when I try to load the library.

```r
devtools::install_github('henry090/fastai')
library(fastai)
```

Error: package or namespace load failed for ‘fastai’ in get(method, envir = envir):
 lazy-load database 'C:/R-libraries/fastai/R/fastai.rdb' is corrupt
In addition: Warning message:
In get(method, envir = envir) : internal error -3 in R_decompress1

Any help to get around this would be much appreciated.

Many thanks,

Mubashir

**Comment by henry090** [comment]
Hi @mubashirqasim . Please restart RStudio after installation.

**Comment by henry090** [comment]
If you still face the same issue, please reopen.
