### ISSUE TITLE
TPU and the fastai wrapper

### ISSUE THREAD

**Issue by Cdk29** [henry090/fastai#111]
Hi,

I was thinking on the how to train xse-resnext-50 in R without going out of memory. Huge networks like this seems to be trained in Pytorch using TPU on Kaggle.

Fastai does not handle directly TPU but there is some wrapper : https://github.com/butchland/fastai_xla_extensions 
Example here : https://www.kaggle.com/johnyquest/tpu-fastai-notebook

I put this as a feature request and a reminder to myself to look into this. As far as I can see it does not seems to much difficult to use TPU with fastai (four pip install and a methods on the learner). 
But I don't have your experience with the wrapper/TPU (As far as I know you are the only person that created a kernel with TPU inside R on kaggle :p )

Is it as "easy" as it seems or is there a problem I do not see ?

**Comment by henry090** [comment]
Hi, It is a valuable feature request!
We can add this to the wrapper. However, we won't be able to test it. In addition,
Is TPU available for R in Kaggle notebooks? For Colab, the answer is "Yes".

**Comment by Cdk29** [comment]
I am inside a R notebook and do not see TPU as an accelerator. But I was pretty sure I have seen some TPU for R notebooks.

It is really odd. Probably I have hallucinated or made a weird association : now we can push R kaggle notebook to google collab also, as do Python notebooks. So maybe we can use TPU on it

**Comment by henry090** [comment]
> So maybe we can use TPU on it

Sure! First, we need to create a wrapper around TPU. 


> kaggle

Around 1 year ago I asked the Kaggle team about that (TPU request) but it seems it is still not added there.
