### ISSUE TITLE
Colab TPU example

### ISSUE THREAD

**Issue by henry090** [henry090/fastai#113]
We need to add a TPU example on Colab. Then add a ref link to the readme file

**Comment by henry090** [comment]
@Cdk29 Hi here is an example. It worked fine. Very soon, I will submit the next release to CRAN (tpu support). https://colab.research.google.com/drive/1PiBECDM552No-5apVIB8LqUSdSqqJSi-?usp=sharing

**Comment by Cdk29** [comment]
Oh nice. Sorry I am not really reactive, most of my coding time goes into the cassava comp. I am glad to see this, I think I will use it for some Knoledge Distillation approach :-)
