### ISSUE TITLE
load_learner does not seems to exist

### ISSUE THREAD

**Issue by Cdk29** [henry090/fastai#115]
load_learner() is the function that allow to load a model that has been exported. It does not seems to exist in the wrapper :

Source : https://docs.fast.ai/learner.html#load_learner

**Comment by henry090** [comment]
Yes, Could you open a PR for that?

**Comment by Cdk29** [comment]
I can try. It is as simple as for freeze methods ?

**Comment by henry090** [comment]
I think, yes, it should be easy. But please write/add a test. So, we will be sure that it won't fail.

**Comment by Cdk29** [comment]
Okay, you can assign me to this if you are not in a big hurry.
