### ISSUE TITLE
Load a model saved with SaveModelCallback?

### ISSUE THREAD

**Issue by oliviergimenez** [henry090/fastai#116]
Thank you very much for an awesome and much needed package. I'm saving a model after each epoch using SaveModelCallback
```r
nb_epoch <- 8
learn %>% fit_one_cycle(nb_epoch, cbs = SaveModelCallback(every_epoch = TRUE, fname = 'model'))
```
Say I'm using a new session, and that I'd like to start from the latest model. Is there a way to load this last model with extension .pth that I stored previously? I guess my question is related to issue #115 I've just seen. 
Thanks in advance.

**Comment by henry090** [comment]
Hi @oliviergimenez. You can restore the model from a fresh R session without training:
```
learn$load("model_1") # change index 1 in the title to 7 if the epoch number is 8 for the last state
```

**Comment by oliviergimenez** [comment]
Embarassingly simple, and works like a charm, thanks a lot !
