### ISSUE TITLE
Error in preprocessing (proc) in Rstudio

### ISSUE THREAD

**Issue by fsame** [henry090/fastai#121]
Hi, 
I tried to run the tabular learner from rstudio. Running **procs = list(FillMissing(),Categorify(),Normalize()),** I get the following error: Error: $ operator is invalid for atomic vectors. Is there a fix for that? Thanks.

**Comment by henry090** [comment]
Hi, Did you try to install ```fast.ai``` following the procedure in readme file? https://github.com/henry090/fastai#installation

**Comment by fsame** [comment]
Thanks a lot for your quick reply. I followed the procedure now, and it works perfectly. Thanks.
