### ISSUE TITLE
AttributeError: module 'fastai.vision.gan' has no attribute 'unet_config'

### ISSUE THREAD

**Issue by houndcl** [henry090/fastai#128]
I am using this tutorial for super resolution Unet model. https://cran.r-project.org/web/packages/fastai/vignettes/super_res_gan.html. However, the `create_gen_learner` function resulted in `Error in py_get_attr_impl(x, name, silent) : AttributeError: module 'fastai.vision.gan' has no attribute 'unet_config'` error. The basic Unet without `unet_config` argument works fine. https://github.com/henry090/fastai#unet-example

```r
create_gen_learner = function() {
  unet_learner(dls_gen, arch, loss_func = loss_gen,
               config = unet_config(blur=TRUE, norm_type = "Weight", 
               self_attention = TRUE, y_range = y_range))
}
learn_gen = create_gen_learner()
# Error in py_get_attr_impl(x, name, silent) :
#     AttributeError: module 'fastai.vision.gan' has no attribute 'unet_config'
```

**Comment by henry090** [comment]
Hi. Thanks for letting me know. From the python side, the tutorial is here. And as far as I understand, this function is no longer in fast.ai. https://github.com/fastai/fastai/blob/master/dev_nbs/course/lesson7-superres.ipynb

```
from fastai.vision.all import *
unet_config(blur=True, norm_type=NormType.Weight)
# NameError: name 'unet_config' is not defined
```

This could be in another place but I am not sure.

**Comment by houndcl** [comment]
Thanks. https://github.com/fastai/fastai/commit/eaa588fdc1efdfdd4a3c1dcae1895add10f223a7#diff-fa360114e1afbe049ed12f6aa92ac3945ceca61d72d73cec953217ddf602a1aa `unet_config` have been changed to `create_unet_model`. Based on my quick reading, it seems right now you can pass the arguments directly to `unet_learner` without calling `unet_config` or `create_unet_model` (please confirm!).

```r
create_gen_learner = function() {
  unet_learner(dls_gen, arch, loss_func = loss_gen,
               blur=TRUE, norm_type = "Weight", 
               self_attention = TRUE, y_range = y_range)
}

learn_gen = create_gen_learner()
# work !
```

**Comment by henry090** [comment]
I think you are right. We need to add this ```create_unet_model```, as well. I can add this. However, if you have time and would like to PR, that would be great!
