### ISSUE TITLE
A function seems to miss into the core module

### ISSUE THREAD

**Issue by pnan997** [henry090/fastai#155]
Hi,  I'm using Python V3.12.3 and built (pip install) fastai 2.7.15 along with torch 2.2.2
I'm trying to implement some machine learning code on stocks. Using tabular module.
I'm getting an error of missing function (see below)
I'm writing because I couldn't find any other helpful internet resource to deal with this problem. 
I've tried to downgrade to earlier versions of  fastai but I'm facing compatibility issues with torch.
If you have the function def, even if you don't want to bother with officially updating anything, just the code to install the function add_cyclic_datepart to insert locally into ...\AppData\Roaming\Python\Python312\site-packages\fastai\tabular\core.py would be greatly appreciated!
Thank you

```
-------------------------------------------------------------------
import yfinance as yf
import pandas as pd 
import numpy as np
from ta import add_all_ta_features
#import fastai
#print(dir(fastai.tabular.core))
from fastai.tabular.core import add_datepart, add_cyclic_datepart
-------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[71], [line 7](vscode-notebook-cell:?execution_count=71&line=7)
      [5](vscode-notebook-cell:?execution_count=71&line=5) #import fastai
      [6](vscode-notebook-cell:?execution_count=71&line=6) print(dir(fastai.tabular.core.A))
----> [7](vscode-notebook-cell:?execution_count=71&line=7) **from fastai.tabular.core import add_datepart, add_cyclic_datepart**

_ImportError: cannot import name 'add_cyclic_datepart' from 'fastai.tabular.core'_
```

**Comment by turgut090** [comment]
This repo is for R version of fast.ai. Your issue is related to python version of fast.ai. Please, refer https://github.com/fastai/fastai
