### ISSUE TITLE
Add automl feature

### ISSUE THREAD

**Issue by henry090** [henry090/fastai#40]
We could add auto ml for tabular data like in ```h2o.automl```.

**Comment by zigzagthad** [comment]
Hi,
Do you mind if I take this up?

**Comment by henry090** [comment]
That would be great! My idea is to tune parameters via Bayesian Optimization like in this [notebook](https://github.com/muellerzr/Practical-Deep-Learning-for-Coders-2.0/blob/master/Tabular%20Notebooks/02_Bayesian_Optimization.ipynb). Later, store and print models from highest to lowest score as in h2o. Could you share your idea, please?

**Comment by zigzagthad** [comment]
That's pretty much it from me as well. After all, doing Random Search or Grid Search isn't an option here because of the large search space so I think Bayesian Search is the way forward.
