### ISSUE TITLE
num workers for Dataloaders

### ISSUE THREAD

**Issue by henry090** [henry090/fastai#93]
If !os=="linux", num_workers always == 0. Fix for all data loaders, e.g. image laoders

**Comment by henry090** [comment]
@Cdk29 There could be potential issues with ```num_workers``` in different data loaders. They all need to be set to 0 if the os is windows or mac. Below is how I do that:

https://github.com/henry090/fastai/blob/a34f08cfa667c179f8b5cd6554d4396cca704942/R/vision_core.R#L551-L561

If you have time and would like to contribute more, that would be great/helpful! =)

**Comment by Cdk29** [comment]
Hehe. So basically add this lines of codes inside the other dataloaders ?

**Comment by henry090** [comment]
Actually, yes. Because without this, the tests for mac and windows hang or fail. See test here: https://github.com/henry090/fastai/blob/master/tests/testthat/test-nn_module.R
In this part, the Tfdml contains above-mentioned part. Therefore, tests are successful. https://github.com/henry090/fastai/blob/a79a21930432c683d7d28eefd6b0a6050d11bc45/tests/testthat/test-nn_module.R#L31-L32

**Comment by Cdk29** [comment]
Okay. Today I will be a bit short for this, but in the next days I can do it.

**Comment by henry090** [comment]
Hi, I currently have time to fix the issues. If you haven't yet started working on this, I can take it.

**Comment by Cdk29** [comment]
@henry090 yes sorry, I did not got time to start working on this. You can take it.
I will do a PR later today but for something related for fine tuning.

**Comment by henry090** [comment]
Done
