### ISSUE TITLE
Suppression of bs_finder.cpython-36.pyc. 🐞

### ISSUE THREAD

**Issue by Cdk29** [henry090/fastai#99]
@henry090 Last [commit](https://github.com/henry090/fastai/commit/06e55ee00a1dff80335919980869a94f7610c6e8) introduced the suppression of inst/python/fastaibuilt/__pycache__/bs_finder.cpython-36.pyc.

I was getting a merging error because of this file, I though I merged the new one of the  henry090 / fastai master branch here in my fork.

I do not know how this file is generated in the first place. Maybe you should check after it.

Edit : looking at my history I did git rm on this file to try to solve the merging error. That was quite stupid, sorry for that. I just that just re indexing the file on your local folder will do the trix.

**Comment by henry090** [comment]
You can skip this file. It does not affect anything.

**Comment by Cdk29** [comment]
Good to know. I was just worried about this. Thanks.
